---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: release-template
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    description: The git revision
    default: master
  - name: repo-full-name
    description: The git repository url
  - name: image-name
  - name: version
    default: latest
  - name: repo-name
  - name: repo-branch
  - name: action
    default: opened
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: go-cd-pipeline-
    spec:
      serviceAccountName: tekton-account
      workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: cd-release-pipeline-claim
      pipelineRef:
        name: go-cd-pipeline
      params:
      - name: revision
        value: $(params.revision)
      - name: repo-full-name
        value: $(params.repo-full-name)
      - name: repo-name
        value: $(params.repo-name)
      - name: version
        value: $(params.version)
      - name: repo-branch
        value: $(params.repo-branch)
      - name: pull-request-action
        value: $(params.action)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: release-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    value: master
  - name: repo-full-name
    value: $(body.repository.full_name)
  - name: repo-name
    value: $(body.repository.name)
  - name: repo-branch
    value: master
  - name: version
    value: $(body.release.tag_name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cd-pipeline-listener-release
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-account
  triggers:
    - name: github-trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-hook
              secretKey: key
            eventTypes:
              - release
      bindings:
        - name: release-binding
      template:
        name: release-template