---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: release-template
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    description: The git revision
    default: master
  - name: repo-full-name
    description: The git repository url
  - name: image-name
  - name: version
    default: latest
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: go-cd-pipeline-
    spec:
      serviceAccountName: tekton-account
      workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: ci-pipeline-claim
      pipelineRef:
        name: go-cd-pipeline
      params:
      - name: revision
        value: $(params.revision)
      - name: repo-full-name
        value: $(params.repo-full-name)
      - name: image-name
        value: $(params.image-name)
      - name: version
        value: $(params.version)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: release-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    value: $(body.head.sha)
  - name: repo-full-name
    value: $(body.repository.full_name)
  - name: image-name
    value: $(body.repository.name)-$(body.head.ref)
  - name: version
    value: latest
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cd-pipeline-listener-release
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-account
  triggers:
    - name: github-trigger
      interceptors:
        - github:
            eventTypes:
              - releases
      bindings:
        - name: cd-binding
      template:
        name: cd-template