apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-manifests
  namespace: tekton-pipelines
spec:
  params:
    - name: template
      default: "manifests.yaml"
    - name: image-name
      default: "IMAGE-NAME"
    - name: version
      default: "VERSION"
    - name: target_url
      default: " "
    - name: github-context
      default: "generate-manifests"
    - name: repo-full-name
    - name: revision
      default: master
    - name: deploy-type
      default: staging
    - name: repo-name
    - name: repo-branch
  results:
    - name: manifest
      description: generated manifest
  workspaces:
    - name: source
      mountpath: /source
  steps:
    - name: generate-manifests
      image: hairyhenderson/sed:latest
      env:
        - name: MASTERVERSION
          valueFrom:
            configMapKeyRef:
              name: master
              key: version
      script: |
        cd /source
        sed -e "s/IMAGE-NAME/$(params.image-name)/g" -e "s/VERSION/$(params.version)/g" -e "s/DEPLOY-TYPE/$(params.deploy-type)/g" -e "s/REPO-NAME/$(params.repo-name)/g" -e "s/REPO-BRANCH/$(params.repo-branch)/g" -e "s/MASTER-VERSION/${MASTERVERSION}/g" $(params.template) > $(params.template).edited
        rm $(params.template)
        mv $(params.template).edited $(params.template)
        cat $(params.template)
        echo $(params.template) > /tekton/results/manifest)
    - name: update-github-finished
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"success\", \"target_url\": \"$(params.target_url)\", \"description\": \"generating manifests finished\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0