---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: go-lint
  namespace: tekton-pipelines
spec:
  params:
  - name: context
    default: .
    type: string
  - name: repo-full-name
    default: ""
  - name: target_url
    default: ""
  - name: github-context
    default: "go-lint"
  - name: revision
    description: revision of the commit to add status updates to
  workspaces:
  - name: source
    mountpath: /source
  results:
    - name: state
      description: state of the next github update
    - name: description
      description: description of the next github update
  steps:
    - name: update-github-started
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        curl -X POST -H 'Content-Type: application/json' --data '{"state":"pending", "target_url": "$(params.target_url)", "description": "started", "context": "'$(params.github-context)'"}' https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0
    - name: go-lint
      image: golangci/golangci-lint:latest
      script: |
        #!/bin/bash
        cd /source/$(params.context)
        golangci-lint run -v | grep ":[0-9][0-9]:[0-9][0-9]:" > /tekton/results/description
        if [ "$?" = 0 ]; then
          printf "success" > /tekton/results/state
        else
          printf "failure" > /tekton/results/state
        fi
        exit 0
    - name: update-github-finished
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        finalstate=success
        while read line; do
          state=failure
          finalstate=failure
          echo $line | cut -d " " -f 1 > context
          context=$(cat context)
          echo $line | cut -d ":" -f 4 > temp.txt
          description=$(sed 's/\`/ /g' temp.txt)
          echo "failure" > /tekton/results/state
          curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"${state}\", \"target_url\": \"$(params.target_url)\", \"description\": \"${description}\", \"context\": \"${context}\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        done < /tekton/results/description
        if [[ $finalstate == "failure" ]]; then
          description="Some linting errors occured"
        else
          description=" "
        fi
        curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"${finalstate}\", \"target_url\": \"$(params.target_url)\", \"description\": \"${description}\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0
