apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-install
  namespace: tekton-pipelines
spec:
  params:
  - name: src
    description: location of helm chart
  - name: target_url
    default: " "
  - name: github-context
    default: "helm-install"
  - name: repo-full-name
  - name: revision
    default: master
  workspaces:
    - name: source
      mountpath: /source
  steps:
  - name: helm-install
    image: alpine/helm:3.2.1
    script: |
      cd /source
      helm uninstall $(repo-full-name)
      helm install $(repo-full-name) $(params.src)
  - name: update-github-finished
    env:
      - name: GITHUBTOKEN
        valueFrom:
          secretKeyRef:
            name: github
            key: token
    image: curlimages/curl:latest
    script: |
      curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"success\", \"target_url\": \"$(params.target_url)\", \"description\": \"deploy yaml finished\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
      exit 0