---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-unit-tests
  namespace: tekton-pipelines
spec:
  params:
  - name: context
    default: .
    type: string
  - name: repo-full-name
    default: ""
  - name: target_url
    default: ""
  - name: context
    default: "go-lint"
  workspaces:
  - name: source
    mountpath: /source
  results:
    - name: state
      description: state of the next github update
    - name: description
      description: description of the next github update
  steps:
    - name: update-github-finished
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        curl -X POST -H 'Content-Type: application/json' --data '{"state":"pending", "target_url": "$(params.target_url)", "description": "started", "context": "'$(params.context)'"}' https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0
    - name: run-ci-test
      image: golang:latest
      script: |
        cd /source/${params.context}
        go test
        if [ "$?" = 0 ]; then
          printf "success" > /tekton/results/state
        else
          printf "failure" > /tekton/results/state
        fi
        exit 0
    - name: update-github-finished
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        state=$(cat /tekton/results/state)
        description=$(cat /tekton/results/description)
        curl -X POST -H 'Content-Type: application/json' --data '{"state":"${state}", "target_url": "$(params.target_url)", "description": "${description}", "context": "'$(params.context)'"}' https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0