apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
  namespace: tekton-pipelines
spec:
  params:
    - name: src
    - name: image-name
    - name: experimental-version
  workspaces:
    - name: source
      mountpath: /source
  steps:
    - name: yq
      image: mikefarah/yq:latest
      env:
        - name: MASTERVERSION
          valueFrom:
            configMapKeyRef:
              name: $(params.image-name)master
              key: version
      script: |
        yq w -i /source/$(params.src) image.master "beppev/$(params.image-name):${MASTERVERSION}"
        yq w -i /source/$(params.src) image.experimental "beppev/$(params.image-name):$(params.experimental-version)"

