
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ci-template
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    description: The git revision
    default: master
  - name: repo-full-name
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: go-ci-pipeline-
    spec:
      serviceAccountName: tekton-account
      workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: ci-pipeline-claim
      pipelineRef:
        name: go-ci-pipeline
      params:
      - name: revision
        value: $(params.revision)
      - name: repo-full-name
        value: $(params.repo-full-name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ci-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repo-full-name
    value: $(body.repository.full_name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ci-pipeline-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-account
  triggers:
    - name: github-trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-hook
              secretKey: key
            eventTypes:
              - push
      bindings:
        - name: ci-binding
      template:
        name: ci-template