apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-pipeline-claim
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: .5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cd-pipeline-claim
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: .5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cd-release-pipeline-claim
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: .5Gi