apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-ci-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: workspace
  params:
    - name: revision
      description: usually sha of commit this pipeline has to run on
    - name: repo-full-name
  tasks:
    - name: github-set-all-status
      taskRef:
        name: github-set-all-status
      params:
        - name: task-names
          value: "git-clone go-lint run-unit-tests"
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - github-set-all-status
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: https://github.com/$(params.repo-full-name)
        - name: revision
          value: $(params.revision)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: deleteExisting
          value: "true"
    - name: go-lint
      workspaces:
        - name: source
          workspace: workspace
      taskRef:
        name: go-lint
      runAfter:
        - git-clone
      params:
        - name: context
          value: "src"
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
    - name: run-unit-tests
      workspaces:
        - name: source
          workspace: workspace
      taskRef:
        name: run-unit-tests
      runAfter:
        - git-clone
      params:
        - name: context
          value: "src"
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
