apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-branch-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: workspace
  params:
    - name: revision
      description: usually sha of commit this pipeline has to run on
      default: master
    - name: repo-full-name
    - name: repo-name
    - name: version
      description: version that the image will be tagged with
    - name: repo-branch
    - name: type
      description: payload type
  tasks:
    - name: git-clone-no-update
      taskRef:
        name: git-clone-no-update
      conditions:
        - conditionRef: is-equal
          params:
            - name: left
              value: "branch"
            - name: right
              value: $(params.type)
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: https://github.com/$(params.repo-full-name)
        - name: revision
          value: $(params.revision)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: deleteExisting
          value: "true"
    - name: generate-values-no-update
      taskRef:
        name: generate-manifests-no-update
      runAfter:
        - git-clone-no-update
      workspaces:
        - name: source
          workspace: workspace
      params: 
        - name: template
          value: $(params.repo-name)/values.yaml
        - name: image-name
          value: $(params.repo-name)
        - name: version
          value: $(params.repo-branch)-latest
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: repo-name
          value: $(params.repo-name)
        - name: repo-branch
          value: $(params.repo-branch)
        - name: revision
          value: $(params.revision)
    - name: helm-install
      taskRef:
        name: helm-install
      runAfter:
        - generate-values-no-update
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: src
          value: $(params.repo-name)
        - name: release-name
          value: $(params.repo-branch)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
