apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-cd-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: workspace
  params:
    - name: revision
      description: usually sha of commit this pipeline has to run on
      default: master
    - name: repo-full-name
    - name: repo-name
    - name: version
      description: version that the image will be tagged with
    - name: repo-branch
    - name: pull-request-action
      default: closed
  tasks:
    - name: github-set-all-status
      taskRef:
        name: github-set-all-status
      conditions:
        - conditionRef: is-not-equal
          params:
            - name: left
              value: "closed"
            - name: right
              value: $(params.pull-request-action)
      params:
        - name: task-names
          value: "git-clone build-and-push-image generate-manifests helm-install"
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - github-set-all-status
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: https://github.com/$(params.repo-full-name)
        - name: revision
          value: $(params.revision)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: deleteExisting
          value: "true"
    - name: build-and-push-image
      taskRef:
        name: build-and-push-image
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: context
          value: src
        - name: image-name
          value: $(params.repo-name)-$(params.repo-branch)
        - name: version
          value: $(params.version)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
    - name: generate-values
      taskRef:
        name: generate-manifests
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: workspace
      params: 
        - name: template
          value: $(params.repo-name)/values.yaml
        - name: image-name
          value: $(params.repo-name)
        - name: version
          value: $(params.version)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: repo-name
          value: $(params.repo-name)
        - name: repo-branch
          value: $(params.repo-branch)
        - name: revision
          value: $(params.revision)
    - name: helm-install
      taskRef:
        name: helm-install
      runAfter:
        - generate-values
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: src
          value: $(params.repo-name)
        - name: release-name
          value: $(params.repo-name)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
    - name: helm-upgrade
      taskRef:
        name: helm-upgrade
      runAfter:
        - generate-values
        - build-and-push-image
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: src
          value: $(params.repo-name)
        - name: release-name
          value: $(params.repo-name)
        - name: repo-full-name
          value: $(params.repo-full-name)
        - name: revision
          value: $(params.revision)
