apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-manifests
  namespace: tekton-pipelines
spec:
  params:
    - name: template
      default: "/source/manifests"
    - name: image-name
    - name: version
    - name: target_url
      default: " "
    - name: github-context
      default: "generate-manifests"
    - name: repo-full-name
    - name: revision
      default: master
    - name: deploy-type
      default: staging
  results:
    - name: manifest
      description: generated manifest
  workspaces:
    - name: source
      mountpath: /source
  steps:
    - name: 
      image: hairyhenderson/sed:latest
      script: |
        if [[]]
        sed -e "s/IMAGE-NAME/$(params.image-name)/g" -e "s/VERSION/$(params.version)/g" -e "s/DEPLOY-TYPE/$(params.deploy-type)/g" /source/$(params.template) > /tekton/results/manifest
    - name: update-github-finished
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: token
      image: curlimages/curl:latest
      script: |
        curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"success\", \"target_url\": \"$(params.target_url)\", \"description\": \"generating manifests finished\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
        exit 0