---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: event-listener-gateway
  namespace: tekton-pipelines
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: http
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-listener-vservice
  namespace: tekton-pipelines
spec:
  hosts:
  - "*"
  gateways:
  - event-listener-gateway
  http:
  - match:
    - headers:
        X-GitHub-Event:
          exact: pull_request 
    route:
    - destination:
        port:
          number: 8080
        host: el-cd-pipeline-listener
  - match:
    - headers:
        X-GitHub-Event:
          exact: push 
    route:
    - destination:
        port:
          number: 8080
        host: el-ci-pipeline-listener
  - match:
    - headers:
        X-GitHub-Event:
          exact: release 
    route:
    - destination:
        port:
          number: 8080
        host: el-cd-pipeline-listener-release